// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC8xOuyHrIFKL84AA50zChtHn3clWqrsE',
    appId: '1:237515682478:web:60528048a81e1e40c0b33f',
    messagingSenderId: '237515682478',
    projectId: 'projectone-92ee0',
    authDomain: 'projectone-92ee0.firebaseapp.com',
    storageBucket: 'projectone-92ee0.appspot.com',
    measurementId: 'G-76YHWYTKZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHCoMvi8od3SDZzZJsLUIlkWIS79l5bKw',
    appId: '1:237515682478:android:cc73539d3fa6f0d3c0b33f',
    messagingSenderId: '237515682478',
    projectId: 'projectone-92ee0',
    storageBucket: 'projectone-92ee0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiw_Bt1nb8gyT2wF4IzgwZqCV_O2Eh11g',
    appId: '1:237515682478:ios:c79fecc6c7988717c0b33f',
    messagingSenderId: '237515682478',
    projectId: 'projectone-92ee0',
    storageBucket: 'projectone-92ee0.appspot.com',
    iosBundleId: 'saher.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiw_Bt1nb8gyT2wF4IzgwZqCV_O2Eh11g',
    appId: '1:237515682478:ios:c79fecc6c7988717c0b33f',
    messagingSenderId: '237515682478',
    projectId: 'projectone-92ee0',
    storageBucket: 'projectone-92ee0.appspot.com',
    iosBundleId: 'saher.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC8xOuyHrIFKL84AA50zChtHn3clWqrsE',
    appId: '1:237515682478:web:dde15c311400026dc0b33f',
    messagingSenderId: '237515682478',
    projectId: 'projectone-92ee0',
    authDomain: 'projectone-92ee0.firebaseapp.com',
    storageBucket: 'projectone-92ee0.appspot.com',
    measurementId: 'G-X9GPQTBZMC',
  );
}
